Avoiding metadiscourse marker and empty words
rhysd/vim.wasm pull request #19
Opened 2018-07-18 05:56 UTC by msrahman07

"This project is very early phase of experiment" --> "This project is an early phase of the experiment"
Line 45: Metadiscourse marker "However" not needed
Line 51: "And almost" --> empty words
Eliminated "But" "And" where sentences started with these

2018-07-18 10:30 UTC, rhysd commented
Well, I'm not an native English user. Your fixes would correct. Let me ask one question. What tool did you use?

2018-07-18 11:57 UTC, msrahman07 commented
Thank you for replying. I didn’t use any tool! I am taking a course on Technical writing and editing where I am learning to write more clearly and simply for the readers.

2018-07-19 08:18 UTC, rhysd commented
Oh, so you did proofreading for this README.md. It's helpful. Let me review your changes.

2018-07-19 08:23 UTC, rhysd requested changes

2018-07-19 08:23 UTC, rhysd commented on README.md
> +WebAssembly frontend for Vim is implemented as a new GUI frontend. C sources are
Two spaces after period are rule of [original README](https://github.com/vim/vim/blob/master/README.md). I don't want to mix multiple rules in one README file (maximum 80 characters per line is also a rule of original README). So please keep two spaces.

2018-07-19 08:23 UTC, rhysd commented on README.md
> +`sleep()`. All UI rendering events are passed to JavaScript layer
Could you update this line as follows? I think original one no longer represents current architecture correctly.

```markdown
`sleep()`.  Rendering UI to `<canvas>` is done in JavaScript layer
```

Could you also consider that max number of characters per one line is 80?

2018-07-22 07:56 UTC, rhysd commented
Please rebase this branch on master. I updated `wasm` branch to the latest upstream.

2018-07-31 19:48 UTC, rhysd commented
@msrahman07 ping

2018-08-10 08:25 UTC, rhysd commented
I'm closing this as no response. If you're still willing to contribute this, please ping me.

2018-08-10 08:25 UTC, closed without merging